brand_name:
  default: "Netdata"
website_url:
  default: "https://netdata.cloud"
logo_url:
  default: ""
mobile_logo_url:
  default: ""
links:
  type: list
  list_type: simple
  default: >-
    Get the Agent, https://learn.netdata.cloud/docs/get, _blank|
    Sign into Cloud, https://app.netdata.cloud, _blank|
    Netdata Learn, https://learn.netdata.cloud, _blank|
    Help, https://netdata.cloud/community, _blank
icons:
  type: list
  list_type: simple
  default: ""
custom_font_awesome_icons:
  type: list
  list_type: simple
  default: ""
